MOUNT_PATH="/src"
BUILD_DIR="build"
BUILD_PATH="$MOUNT_PATH/$BUILD_DIR"
DOCKER_IMAGE="risteaandrei/ubuntu_cpp_gtest"
RUN="docker run --rm -v $(PWD)/..:$MOUNT_PATH -p 11234:11234 $DOCKER_IMAGE bash -c "
